layout_spectrum: 0.5514861980918795
typography_spectrum: 0.24900537193752825
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.49407746619544923
  lightness: 0.048389959847554564
  saturation: 0.5286679991986603
  rhythmicContrast: 0.6811008828226477
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: can_zop
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Seen By Zoulou
description: Fashion blogger
purpose: []
